version: "3.7"

x-loki: &loki
  image: grafana/loki:v0.4.0
  volumes:
    - ./config/loki.yaml:/config/loki.yaml
  restart: always
  entrypoint: sh
  command: -c "loki -config.file=/config/loki.yaml -target=$$LOKI_TARGET"
  networks:
    - loki
  depends_on:
    - scylla
    - minio
    - consul

networks:
  loki:

volumes:
  chunks:
  index:
  promtail_positions:

services:
  loki-distributor:
    <<: *loki
    environment:
      LOKI_TARGET: distributor

  loki-ingester:
    <<: *loki
    environment:
      LOKI_TARGET: ingester

  loki-querier:
    <<: *loki
    environment:
      LOKI_TARGET: querier

  loki-table-manager:
    <<: *loki
    environment:
      LOKI_TARGET: table-manager

  scylla:
    image: scylladb/scylla
    volumes:
      - index:/var/lib/scylla
    networks:
      - loki

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - chunks:/export
    environment:
      MINIO_ACCESS_KEY: loki
      MINIO_SECRET_KEY: loki_0123456789
    entrypoint: sh
    command: -c 'mkdir -p /export/lokichunks && minio server /export'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - loki

  consul:
    image: consul
    command: agent -log-level=info -dev -client 0.0.0.0
    networks:
      - loki

  promtail:
    image: grafana/promtail:v0.4.0
    volumes:
      - /var/log:/var/log
      - ./config/promtail.varlogs.yml:/config/promtail.yaml
      - promtail_positions:/export
    command: -config.file=/config/promtail.yaml
    networks:
      - loki
    depends_on:
      - loki-distributor

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
