version: "3.7"

networks:
  loki:

volumes:
  chunks:
  index:

services:
  loki:
    image: grafana/loki:v0.4.0
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki.yaml:/config/loki.yaml
    restart: always
    command: -config.file=/config/loki.yaml
    networks:
      - loki
    depends_on:
      - scylla
      - minio
      - consul

  scylla:
    image: scylladb/scylla
    volumes:
      - index:/var/lib/scylla
    networks:
      - loki

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - chunks:/export
    environment:
      MINIO_ACCESS_KEY: loki
      MINIO_SECRET_KEY: loki_0123456789
    entrypoint: sh
    command: -c 'mkdir -p /export/lokichunks && minio server /export'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - loki

  consul:
    image: consul
    networks:
      - loki

  promtail:
    image: grafana/promtail:v0.4.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - loki
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
