version: "3.7"

networks:
  loki:

services:
  loki:
    image: grafana/loki:v0.4.0
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki.yaml:/config/loki.yaml
    command: -config.file=/config/loki.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:v0.4.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
